baseURL = "/"
title = "GitHub Style"
googleAnalytics = ""
theme = "github-style"

[params]
  author = "Billy Liggins"
  description = "My site"
  github = "billyliggins"
  twitter = "billyliggins"
  email = "billyliggins@gmail.com"
  utterances = "example/example.github.io"
  avatar = "https://avatars3.githubusercontent.com/u/13217584?s=400&v=4"
  url = "https://liggins-hep.com"
